on:
    push:
      branches: [main]
    pull_request:
        branches: [main]
        types: [opened, synchronize]

env:
    CI: true

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint
    Test:
        needs: [Lint]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Start server
              run: npm run server
        
            - name: Start frontend
              run: npm run dev 

            - name: Wait for server to start
              run: |
                echo "Waiting for server to start..."
                sleep 10 # Adjust the sleep time as needed
            
            - name: Install Playwright browsers
              run: npx playwright install

            - name: Run tests
              run: npm run test
    Tag_release:
        name: Tag Release
        needs: [Lint, Test]
        runs-on: ubuntu-latest
        permissions:
            contents: 'write' # Required to push new tags
        # Skip tagging if the commit message contains #skip for push events or if PR title contains #skip
        if: |
          ${{ 
            github.event_name == 'push' && 
            github.ref == 'refs/heads/main' && 
            !contains(github.event.head_commit.message, '#skip')
          }}
        outputs:
            tag: ${{ steps.tag_version.outputs.tag }}
            changelog: ${{ steps.tag_version.outputs.changelog }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.7
              with:
                fetch-depth: 0 # Required for changelog generation

            - name: Bump version and push tag
              id: tag_version
              uses: anothrNick/github-tag-action@1.73.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                TAG_PREFIX: v
                DEFAULT_BUMP: patch

            - name: Log new tag
              run: echo "New tag is ${{ steps.tag_version.outputs.tag }}"
    Notification:
        runs-on: ubuntu-latest
        needs: [Tag_release]
        if: |
          ${{ 
            always() && 
            github.event_name != 'pull_request' && 
            !contains(github.event.head_commit.message, '#skip') 
          }}
        steps:
          - name: Determine Status
            id: status_check
            run: |
              if [[ "${{ needs.Tag_release.result }}" == "failure" ]]; then
                echo "status=failure" >> $GITHUB_OUTPUT
                echo "color=15548997" >> $GITHUB_OUTPUT
                echo "status_text=Failed" >> $GITHUB_OUTPUT
              else
                echo "status=success" >> $GITHUB_OUTPUT
                echo "color=5763719" >> $GITHUB_OUTPUT
                echo "status_text=Success" >> $GITHUB_OUTPUT
              fi

          - name: Send Discord notification
            uses: sarisia/actions-status-discord@v1
            with:
              webhook: ${{ secrets.DISCORD_WEBHOOK }}
              status: ${{ steps.status_check.outputs.status }}
              color: ${{ steps.status_check.outputs.color }}
              username: "GitHub Actions"